### ISSUE TITLE
Problem regarding the Search bar position 

### ISSUE THREAD

**Issue by ayush-848** [piyushg-07/blogzen-OpenSource#114]
![image](https://github.com/piug-07/blogzen-OpenSource/assets/126975547/9409b421-f400-4299-9bbd-8898460d9acb)

The search bar is covering a part of the 'g' in Blogzen

**Comment by ayush-848** [comment]
Please assign this issue to me.

**Comment by Jasjeevthecoder** [comment]
Kindly Assign it to me . I have great experience of frontend animations
