### ISSUE TITLE
ChatBot error!!!

### ISSUE THREAD

**Issue by Anjaliavv51** [piyushg-07/blogzen-OpenSource#121]
![image](https://github.com/piug-07/blogzen-OpenSource/assets/154777864/a6f1e969-9c46-4056-92d5-e8f0f8e33e1f)

Chabot is not working.
I would like to make it work....
Under GSSOC'24

**Comment by Prachiii8287** [comment]
I would like to solve this issue. Please assign me

**Comment by Anjaliavv51** [comment]
Please add labels Under GSSOC'24
