### ISSUE TITLE
Fix Calendar dark mode UI

### ISSUE THREAD

**Issue by Piyusharora2003** [piyushg-07/blogzen-OpenSource#143]
current version : 
![image](https://github.com/piug-07/blogzen-OpenSource/assets/74443858/d8f90fa0-9cd0-4113-9061-5da3eb035516)
![image](https://github.com/piug-07/blogzen-OpenSource/assets/74443858/db62d76d-cf4b-4be3-94af-d10bc62bbbf5)

I did like to enhance the calendar component UI and correct the dark mode Bug under GSSOC . Please assign me this

**Comment by Kbageja** [comment]
I would like to work on it , please assign this to me
