### ISSUE TITLE
Fixing the position of cards and footer

### ISSUE THREAD

**Issue by Dynamic-Aryan** [piyushg-07/blogzen-OpenSource#144]
The cards below the trending section ,,are not placed perfectly ,,so i can fixed it ,, and the footer is also not looking good,,  means  the social media icons ,, they are small ,,so i can increase their size   and the subscribe to our newsletter and contact us should be in vertical ,,please assign me this under GSSOC'24 ,,i can do it
Thank You @piug-07

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
