### ISSUE TITLE
Missing File Code of conduct

### ISSUE THREAD

**Issue by Parimalasri13** [piyushg-07/blogzen-OpenSource#145]
Code of conduct file is missing and i am a GSSOC 24 contributor can yo please assign this task to me @piug-07  @Riyasharma28

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.

**Comment by soumya813** [comment]
@piug-07 I'd like to propose to revamp the README for this project to improve clarity and accessibility, boosting user engagement and contributions.
please assign this task to me under GSSOC'24

**Comment by n14rishitha** [comment]
Hi @piug-07
the code of conduct takes effect (on issues and pull requests, or community activities like events?). Adopting, and enforcing, a code of conduct can help create a positive social atmosphere for your community. 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3
