### ISSUE TITLE
like and comments button are not functional

### ISSUE THREAD

**Issue by Kbageja** [piyushg-07/blogzen-OpenSource#147]
number should be updated on clicking like button which is not happening , i would like to fix this issue , please assign thsi task to me

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.

**Comment by ShravaniPathak** [comment]
I would like to work on this issue. Please assign this task to me

**Comment by PadmalathaKasireddy** [comment]
Interest in Contributing Blogzen project  as GSSoC contributer.  Eager to learn more and lend a hand! please assign me this issue to sort .
