### ISSUE TITLE
[New Feature] Adding Home, About, Contact us -section

### ISSUE THREAD

**Issue by Yuvasri-b** [piyushg-07/blogzen-OpenSource#160]
Description: 
The Blogzen misses - Home ,About and Contact us page

Screenshots:
![Screenshot 2024-05-13 230411](https://github.com/piug-07/blogzen-OpenSource/assets/155957336/90fd482b-3d24-443b-a4a6-798c5c7e4e2d)

I agree with the contributing gudliness for this project.

Please assign me this issue under GSSOC'24.

**Comment by Aradhya-005** [comment]
I would like to work on this feature . Please assign it to me

**Comment by Yuvasri-b** [comment]
@piug-07   Please assign this issue to me under GSSOC'24
