### ISSUE TITLE
buttons in home page needs some improvement

### ISSUE THREAD

**Issue by reshamsai150** [piyushg-07/blogzen-OpenSource#162]
buttons are not attractive, making its UI better is needed 
![image](https://github.com/piug-07/blogzen-OpenSource/assets/164533685/b27d95f2-0745-4d86-8eaf-6eea68906224)
assign this issue  to me@piug-07

**Comment by Adilkhan056** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Aradhya-005** [comment]
I would like to work on this . Please assign to it to me

**Comment by niteshbca** [comment]
Please assign to me task

**Comment by KARTHIK174** [comment]
I would like to work on this . Please assign to it to me

**Comment by amruthavarshinikodali** [comment]
I want to work on this as a part of GSOC'24 contributor please assign this task to me @Piyush Gupta
