### ISSUE TITLE
Improving CSS 

### ISSUE THREAD

**Issue by YukiP7** [piyushg-07/blogzen-OpenSource#166]
![Screenshot 2024-05-14 133856](https://github.com/piug-07/blogzen-OpenSource/assets/109288720/5ce0f62e-9c1d-441d-9c0d-d4ee57dad961)
Hello there! I have noticed some CSS bugs on your website that are affecting its appearance. Specifically, there seems to be inconsistent spacing between options such as "All" and "Technology". This can make the website look less presentable and not match its overall design. It would be great to have an equal amount of space between all options to improve the website's appearance.

![Screenshot 2024-05-14 133932](https://github.com/piug-07/blogzen-OpenSource/assets/109288720/ac3eed7a-9b29-45d0-bf92-0d59565ef138)
Adding a proper space in b/w these cards 

Also on dark mode calendar and login details is not visible properly 
![Screenshot 2024-05-14 141756](https://github.com/piug-07/blogzen-OpenSource/assets/109288720/f8faeef2-cddf-404b-af0b-182ac0c4895e)

![Screenshot 2024-05-14 141806](https://github.com/piug-07/blogzen-OpenSource/assets/109288720/39ff3e99-e095-401a-a9fd-c1dd8fe24c5b)

**Comment by YukiP7** [comment]
I would like to request that this issue be labeled as Gssoc, and please assign me the task of correcting it.

**Comment by Sowmyatiwari** [comment]
Hey there , I am contributing to gssoc'24 , I have noticed improper alignment and css bugs in your website , I have a prior experience in building websites , and also worked on blog applications earlier. please assign this task to me , I will fix this bug .
