### ISSUE TITLE
Contact us section not arranged properly

### ISSUE THREAD

**Issue by Harsh22428** [piyushg-07/blogzen-OpenSource#175]
![Screenshot 2024-05-14 164041](https://github.com/piug-07/blogzen-OpenSource/assets/143131675/8e433c68-d210-4728-a29e-16c4ab3eeadf)

Contact us section is not properly arrange which is not good looking 
I can solve this issue make it more beautiful and arranged very well
Please assign me this issue GSSOC'24
Thank You

**Comment by usharani222** [comment]
Assign me this issue

**Comment by maniranjan2023** [comment]
please, Assign me this issue

**Comment by prithu12** [comment]
Assign me this issue

**Comment by Ananyarawa8t** [comment]
Hey @piug-07,
I would like to contribute to this project , Please assign this issue to me under GSSOC'24.
Best Regards,
Ananya Rawat

**Comment by mtg718** [comment]
Hey @piug-07,
I would like to contribute to this project , Please assign this issue to me under GSSOC'24.

**Comment by Supraja-Gao** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by Aryan-joh** [comment]
Hii as i am an Web developer s i can mange this issue and can provide the best solution .... so assign this to me
