### ISSUE TITLE
difficulty in visibility of text in dark mode and enhancement in nav bar buttons and hovering effect!!

### ISSUE THREAD

**Issue by NeerajaGurram** [piyushg-07/blogzen-OpenSource#178]
in dark mode text in calender is not visible 
![image](https://github.com/piug-07/blogzen-OpenSource/assets/152693538/eb6452f3-dc7c-4280-8942-01e037c4a9bf)
login page too has the same problem
![image](https://github.com/piug-07/blogzen-OpenSource/assets/152693538/2f068af7-23c7-4c67-ac63-79ca7b1de4d1)

nav bar ('all','technology',....) buttons and hovering effects can be improved in the dark mode!

please label this issue as gssoc and give appropriate level

please assign me this. :)

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24
