### ISSUE TITLE
Adding the copyright details at the footer section

### ISSUE THREAD

**Issue by Saimanjari777** [piyushg-07/blogzen-OpenSource#180]
The copyright details are missing on the footer section.  
![image](https://github.com/piug-07/blogzen-OpenSource/assets/130165687/4f33c260-750b-4aee-b508-9972360673b7)
I want to work on this issue.
please assign the task to me @piug-07.

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24
