### ISSUE TITLE
No hover  effect on all button

### ISSUE THREAD

**Issue by rajvaidyanath27** [piyushg-07/blogzen-OpenSource#183]
When clicking on the all button there is no hover effect

**Comment by Mdazar123** [comment]
I'm proficient in design and have a strong grasp of CSS. Please consider assigning this task to me.

**Comment by chakrabortydeep** [comment]
![Screenshot 2024-05-15 162258](https://github.com/piug-07/blogzen-OpenSource/assets/146315717/7287295e-3870-4fb4-9e49-1d3ad82d86d2)

There is no hover effect on Log in, Sign Up and Calender buttons. I can fix that easily and effectively with animation. Please assign that task to me.
