### ISSUE TITLE
Different  sizes of nav box

### ISSUE THREAD

**Issue by rajvaidyanath27** [piyushg-07/blogzen-OpenSource#184]
As you can see in the below image while i am switching  on the  darkmode the div sizes look kinda odd which creates a bad UI. so i want to work on this  CSS . @piug-07  kindly assign me this issue
![Screenshot 2024-05-14 234058](https://github.com/piug-07/blogzen-OpenSource/assets/132011829/e75000a7-71e0-4fb5-880e-0ad2764800fb)

**Comment by jahnaviyallamelli** [comment]
i would like to work on this issue please assign this task to me
