### ISSUE TITLE
Adding GitHub icons

### ISSUE THREAD

**Issue by codewithishu** [piyushg-07/blogzen-OpenSource#187]
GitHub icons should be added to allow the users to get the code and review it

**Comment by codewithishu** [comment]
@piug-07 please label it and assign this issue to me

**Comment by anushreenair** [comment]
assign this issue to me

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by shubham6m** [comment]
please assign this issue to me for making a unique changes

**Comment by barachaman04** [comment]
s a GSSOC'24 Contributor, I'm keen to elevate the visual appeal of our web page by integrating GitHub icons. Kindly assign me this task. Appreciate your support!

**Comment by vanshikasingh11** [comment]
Seeking to elevate the visual appeal, I propose updating GitHub icons on the web page. As a GSSOC'24 Contributor, please assign me this task. Thank you!
