### ISSUE TITLE
Calender dates not visible in dark mode

### ISSUE THREAD

**Issue by kritzxd8** [piyushg-07/blogzen-OpenSource#188]
hello @piug-07 , i am kritika , a fellow contributor in GSSoC24. 
The calender dates are not visible when we switch to dark mode. I am willing to solve this issue . Kindly assign it to me .
![Screenshot 2024-05-15 094230](https://github.com/piug-07/blogzen-OpenSource/assets/162461631/27ba94cf-d4ef-4d2f-a60f-c32b4cff6a8f)

- [ ] I have followed the contribution guidelines 
- [ ] I have starred your repo
- [ ] I have analysed the issue 

note : kindly add label while assigning the issue to me

**Comment by kritzxd8** [comment]
- [x] i have starred your repo
- [x] i have followed the contribution guidelines
- [x] i have analysed the isse

**Comment by usharani222** [comment]
i would like to work on this .Assign me this issue

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24
