### ISSUE TITLE
Improving Navbar, Buttons and spacing in the content

### ISSUE THREAD

**Issue by Dhruv-Gaba** [piyushg-07/blogzen-OpenSource#203]
### Description
The navbar is not eye catching and it also does not change in dark mode. The alignment and size of buttons are also not up to the mark. Aligning them properly and applying hover effects to the buttons can make the website look better. the content on the webpage is overlapping and looks chaotic.

The navbar styling can be improved and it can be made sensitive to dark mode.
![image](https://github.com/piug-07/blogzen-OpenSource/assets/141745373/1ca2e914-783d-42d9-8f49-0bf252751e0c)

The button sizes and spacing is highly uneven.
![image](https://github.com/piug-07/blogzen-OpenSource/assets/141745373/b62f831b-fc60-4ecc-8390-32dd6108766d)

The content overlaps.
![image](https://github.com/piug-07/blogzen-OpenSource/assets/141745373/f289997f-45e6-4357-8884-93f0a48941ac)

I wish to work on the above stated issues. Please assign me this issue GSSOC'24 @piug-07 .
**Thank you**

**Comment by NSG18** [comment]
i want to  work on this please  assign me @piug-07
