### ISSUE TITLE
Create a signup page

### ISSUE THREAD

**Issue by Heena31** [piyushg-07/blogzen-OpenSource#206]
I would like to create a signup page. I can create attractive signup page. As a contributer, I would like to contribute

**Comment by aasthax1** [comment]
I have made many full stack projects which include login,signup page.So i am very much confident that i will be able to fix this issue.Please assign me this task.Thank you.

**Comment by namandude** [comment]
Hey I would like to help you in creating  the the clean and attractive authentication page. 
I like to contribute in this please assign it .
Thank You!
