### ISSUE TITLE
Improving the navbar

### ISSUE THREAD

**Issue by paridhi1509** [piyushg-07/blogzen-OpenSource#218]
The navigation bar on the top doesn't sit well with the whole page and i would like to work on it.

**Comment by unnatinarayan** [comment]
Please assign me this issue. I would work on creating a better navbar both responsive and I will fit it in an hamburger menu for shorter width devices. I want to contribute under GSSOC'2024.

**Comment by jahnaviyallamelli** [comment]
please assign this task to me the nav bar is not attractive i can solve this issue
