### ISSUE TITLE
hover effect on header icons

### ISSUE THREAD

**Issue by Ishmeetkaur36** [piyushg-07/blogzen-OpenSource#220]
uniform hover over all header icons sign up ,login in ,calendar

**Comment by vanirastogi** [comment]
hi can u assign it to me i can fix it

**Comment by Kalyan9064** [comment]
#211

**Comment by chakrabortydeep** [comment]
The hover effect on the header buttons are not working properly. Assign me this task to change the css of the buttons.

**Comment by jahnaviyallamelli** [comment]
i want to work on this issue you can assign this to me

**Comment by ARPITBAJPAI0098** [comment]
hello boss can you pls assign this issue to me i am having 1year of experience in Mern stack currently serving as the Technical Executive  of Sphnix largest techfest of Rajasthan under NIT jaipur
