### ISSUE TITLE
sign up button is not working 

### ISSUE THREAD

**Issue by vanirastogi** [piyushg-07/blogzen-OpenSource#223]

**Comment by vanirastogi** [comment]
Hi can u assign it me under Gssoc 2024 . I will fix it

**Comment by NamanJain795** [comment]
Hi @piug-07 I am Naman Jain a Gssoc'24 contributor
In your webpage signup option is not available
Can u please assign me the task to make a signup page for your website and tell your requirements also according to that it can be prepared.
Looking for your response
THANK U
