### ISSUE TITLE
Readme.md can be more fascinating 

### ISSUE THREAD

**Issue by Meetjain1** [piyushg-07/blogzen-OpenSource#230]
currently our readme.md file is not upto the mark it is not capturing contributors to it due to some few missing elements like 
working video of our project , missing icons , Text allignment , missing images , Contributors section not placed in good position , using badge instead of icons in techstack and many more 

@piug-07 assign this issue to me I will add these things and make readme file more attractive and fascinating . Thankyou 
 I am working under gssoc 24.

**Comment by Akshitha28112004** [comment]
Hey, I've already worked on a readme file for another project. Feel free to check it out in my profile. So can you please assign me this issue under gssoc'24?
