### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by visioncoding021** [piyushg-07/blogzen-OpenSource#242]
# Dark theme is not properly work . i want to resolve this issue please assign me this 
![Screenshot 2024-05-19 204943](https://github.com/piug-07/blogzen-OpenSource/assets/75429646/264ffce6-b439-489a-b867-242f7d5cb95b)

**Comment by visioncoding021** [comment]
@piug-07

**Comment by ARPITBAJPAI0098** [comment]
hello boss can you pls assign this issue to me i am having 1year of experience in Mern stack currently serving as the Technical Executive  of Sphnix largest techfest of Rajasthan under NIT jaipur

**Comment by visioncoding021** [comment]
Please reply??
