### ISSUE TITLE
Navbar not responsive to the dark mode

### ISSUE THREAD

**Issue by shreyashiawasthi** [piyushg-07/blogzen-OpenSource#245]
The dark mode is not working properly and the navbar still remains white after switching to the dark theme. Assign me this issue so that I can make the website fully responsive to Dark Mode.

![Screenshot 2024-05-20 115150](https://github.com/piug-07/blogzen-OpenSource/assets/146011136/80707e24-b779-43f1-b0b8-565c6c423be9)

**Comment by ARPITBAJPAI0098** [comment]
hello boss can you pls assign this issue to me i am having 1year of experience in Mern stack currently serving as the Technical Executive  of Sphnix largest techfest of Rajasthan under NIT jaipur
