### ISSUE TITLE
calendar  dates not showing properly in dark mode

### ISSUE THREAD

**Issue by Anshika-Gochar** [piyushg-07/blogzen-OpenSource#249]
we need to make changes so that dates of calendar are visible in dark mode as well here is the screenshot of the issue
![blogzen issue](https://github.com/piug-07/blogzen-OpenSource/assets/148606019/152a48c4-a2c6-4cd6-8b4f-391a4bc54e49)
i can fix this so please assign me this under GSSoc'24.

**Comment by RohitGo8789** [comment]
Can you assign me this, I think I can fix this!!
