### ISSUE TITLE
Making footer section more attractive 

### ISSUE THREAD

**Issue by Anshika-Gochar** [piyushg-07/blogzen-OpenSource#250]
the footer section can be made more attractive and more content can be added
![blogzen2](https://github.com/piug-07/blogzen-OpenSource/assets/148606019/3189b810-3860-4a74-b11c-4d58f021662f)
assign me this please under GSSoc'24.

**Comment by EmazinUs** [comment]
@piug-07, I would like to fix this issue. Please do assign me this under GSSOC'24.

**Comment by Divi-1026** [comment]
@piug-07 please assign this issue to me .
* I will ensure to make footer more attractive by adding colors on icon to look it more attractive .
* i will add more content like in contact i willl also add instagram link discord link 
* i will give it more attractive bg color 
please assign this to me

**Comment by harshcodesit** [comment]
hey @piug-07 ,
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the Footer in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .

**Comment by Ananyajain2004** [comment]
Hey I am Ananya Jain ,I am a contributor for the session 24 in GSSOC . please assign me this issue , I believe that I can make it more impressive .

**Comment by Komalpreet-Kaur112** [comment]
Hey @piug-07 
I would also like to work on this issue and enhance the overall look of footer section.
Please assign it me.

**Comment by Meghana-n10** [comment]
Hey i really want to contribute to this project, seems interesting. Please assign me the issue
