### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by Divi-1026** [piyushg-07/blogzen-OpenSource#255]
![Screenshot 2024-05-25 163535](https://github.com/piug-07/blogzen-OpenSource/assets/152860478/43b06e73-44f4-439f-91cf-450f8a62377c)
after navbar create one one div to show this search box and all other item like news al management and give it bg color to look more attractive 

please assign this issue to me i will make header section more attractive

**Comment by vishal02527** [comment]
@piug-07 kindly add labels on this issue and assign this issue to me. I want to do work on this issue to make hover effect on the list items.
