### ISSUE TITLE
Optimizing the CSS

### ISSUE THREAD

**Issue by Shivam250702** [piyushg-07/blogzen-OpenSource#260]
CSS of the site is not proper,cards are overlapping one over the other,text size is small and design not proper

![image](https://github.com/piug-07/blogzen-OpenSource/assets/103785990/355f2636-bb30-4d25-81ba-fa2c4254180d)
****

**Comment by Ananya-Nair20** [comment]
Hello @piug-07 

I am participating in GSSOC'24. I am interested in resolving this issue. Could you please assign this issue to me under GSSOC'24?

Thank you
