### ISSUE TITLE
Adding Features in UI

### ISSUE THREAD

**Issue by Saumyatri** [piyushg-07/blogzen-OpenSource#263]
The Home page and buttons do not have a hover effect.
![image](https://github.com/piug-07/blogzen-OpenSource/assets/111524502/7e7e9a6a-ab2f-4aa3-9237-8608649007e0)
The dark mode doesn't have a proper hover effect and the UI looks different this could be beautified.
![image](https://github.com/piug-07/blogzen-OpenSource/assets/111524502/58e34863-4189-45ca-aa2e-242b87fae1ae)
Adding the much-needed features to the UI.

**Comment by Saumyatri** [comment]
@piug-07 Kindly assign me this issue. I can work on it.

**Comment by vishal02527** [comment]
@piug-07 please assign this issue to me, I can work on this issue in a less time.

**Comment by Yash-Ainapure** [comment]
@Saumyatri  are you working on it?
if no @piug-07 , Can you assign it to me?

**Comment by Saumyatri** [comment]
I am working on it.

**Comment by Yash-Ainapure** [comment]
> I am working on it.

It's been 3 days up now,so i just asked.
no problem

**Comment by Saumyatri** [comment]
@piug-07 approve the pull request Adding Features in UI #385. I have made the changes.
