### ISSUE TITLE
Adding proper spacing in images and content 

### ISSUE THREAD

**Issue by suhanigupta23** [piyushg-07/blogzen-OpenSource#267]
We can add the image and the information links in a particular box so that all of them appears separately in different divisions. which will give  proper spacing between content and images and separate each of them.
<img width="1440" alt="Screenshot 2024-05-27 at 7 10 28 PM" src="https://github.com/piug-07/blogzen-OpenSource/assets/144280247/46d355b7-2a60-4c42-a49f-bdbf7f90d28f">

Please assign me this issue under GSSoc '24.

**Comment by pragneshborad** [comment]
I would like to work on this issue @piug-07 , please assign me this issue.
