### ISSUE TITLE
improving the over effect at header and change button to flex at header

### ISSUE THREAD

**Issue by shuhaki** [piyushg-07/blogzen-OpenSource#274]
improve the hover effect at  header
change button to flex

<img width="623" alt="Screenshot 2024-05-28 at 1 37 11 AM" src="https://github.com/piug-07/blogzen-OpenSource/assets/145912232/033bc82a-3d6c-4384-b430-da18237bda74">

**Comment by niteshbca** [comment]
@shuhaki please assign to me task.
