### ISSUE TITLE
bug - on hovering social media logo , double boxes are visible 

### ISSUE THREAD

**Issue by dvnshi** [piyushg-07/blogzen-OpenSource#278]
![Screenshot 2024-05-28 111506](https://github.com/piug-07/blogzen-OpenSource/assets/138151026/5382d78c-3a28-4c09-9693-ebc0b1223a69)

Description of the Issue Bug
Problem:
When hovering over the social media login options in the popup modal (such as "Sign in with Email", "Sign in with Facebook", etc.), double boxes are visible around the icons. This is likely due to conflicting or redundant CSS styles that are being applied to the elements.

Visual Evidence:
The provided screenshot shows that when hovering over the social media icons in the login popup modal, two boxes (a blue outline and a black outline) are simultaneously visible around the icons.

Expected Behavior:
When hovering over the social media login options, only a single border or outline should be visible, providing a clean and consistent user experience.

Steps to Reproduce:
Open the Blogzen web page.
Click on the "Log In" button to open the login popup modal.
Hover over any of the social media login options.
Observe the double boxes appearing around the icons.

**Comment by dvnshi** [comment]
@piug-07  please assign me the issue raised by me I can work on it under GSSoC24 with lables

**Comment by niteshbca** [comment]
@piug-07 please assign to me task.
