### ISSUE TITLE
Adding more details to the footer

### ISSUE THREAD

**Issue by Chelsea67jain** [piyushg-07/blogzen-OpenSource#282]
I observed that some details are missing in the footer such as rights reserved.
We can add the below line in the footer.
© 2024 BlogZen. All rights reserved.

Before:
![Screenshot (559)](https://github.com/piug-07/blogzen-OpenSource/assets/100270122/48257576-b479-4959-b7d0-90c0f048aef7)

I can add something like this on the footer.
![Screenshot (560)](https://github.com/piug-07/blogzen-OpenSource/assets/100270122/259ac4f6-7213-4fcb-af40-31f4fe581af0)

@piug-07 I would like to work on this issue. Can you assign me this issue under GSSoC24?

**Comment by mfatima05** [comment]
I have assigned this issue to you. Now you can work on it.

**Comment by Chelsea67jain** [comment]
@mfatima05 Thanks for assigning me this issue. I am working on it. Also, can you add gssoc and level1 label separately?
