### ISSUE TITLE
Adding Responsiveness to the navbar

### ISSUE THREAD

**Issue by Chelsea67jain** [piyushg-07/blogzen-OpenSource#283]
## Description:
The navbar is not responsive for a screen size less than 570px i.e. not responsive for mobile devices. I can make it responsive using media queries and a grid.

## Screenshot:
![WhatsApp Image 2024-05-28 at 16 08 36](https://github.com/piug-07/blogzen-OpenSource/assets/100270122/8fc2db4f-578b-47a8-8b9a-cb749e38ed2c)

## References:
https://www.w3schools.com/howto/howto_js_topnav_responsive.asp
https://youtu.be/oLgtucwjVII?si=M4rQ9eC5cecZ31Wu

@piug-07 I would like to work on this issue. Can you allocate this issue under GSSoC24?

**Comment by niteshbca** [comment]
@Chelsea67jain please assign to me task and solve the problem.
