### ISSUE TITLE
Improving UI by adding responsiveness to the footer

### ISSUE THREAD

**Issue by Chelsea67jain** [piyushg-07/blogzen-OpenSource#284]
## Description:
I noticed that the footer is not responsive for different devices. I can add the responsiveness to the footer for every screen size using media query and grid.

## References:
https://www.w3schools.com/html/html_responsive.asp
https://youtu.be/oLgtucwjVII?si=M4rQ9eC5cecZ31Wu

@piug-07 I would like to work on this issue. Can you assign this issue under GSSoC24?

**Comment by niteshbca** [comment]
@Chelsea67jain please assign to me task and solve the problems.

**Comment by Chelsea67jain** [comment]
@niteshbca I am not the author of the repo.
