### ISSUE TITLE
add issues template

### ISSUE THREAD

**Issue by mahek0620** [piyushg-07/blogzen-OpenSource#296]

**Comment by mahek0620** [comment]
@piug-07 Kindly assign this task to me under gssoc'24 and please add labels to it

**Comment by mfatima05** [comment]
kindly explain your created issue

**Comment by mahek0620** [comment]
It doesn't contain any template so adding template 
![image](https://github.com/piug-07/blogzen-OpenSource/assets/136893675/03c3600d-3afc-4722-bdf9-689698cc6af0)

![image](https://github.com/piug-07/blogzen-OpenSource/assets/136893675/899902f9-bb11-41b6-b0cc-1f81726d21fb)
![image](https://github.com/piug-07/blogzen-OpenSource/assets/136893675/bf91365e-19a1-4187-a998-6b0af451ecc4)

**Comment by mfatima05** [comment]
kindly explain it more
