### ISSUE TITLE
Enhance the Chat-Bot Icon

### ISSUE THREAD

**Issue by aindrelasaha** [piyushg-07/blogzen-OpenSource#299]
I want to increase the visibility of the chat bot by giving a whole new icon to the chat bot
![image](https://github.com/piug-07/blogzen-OpenSource/assets/126545390/3d516773-7d24-4a1f-92fe-09bb8cbd5ba5)

**Comment by mfatima05** [comment]
I have assigned this issue to you. Now you can work on it.

**Comment by aindrelasaha** [comment]
Okay Ma'am Thank you
