### ISSUE TITLE
Bug - Overlapping of different sections

### ISSUE THREAD

**Issue by Amitanand0123** [piyushg-07/blogzen-OpenSource#308]
![image](https://github.com/piug-07/blogzen-OpenSource/assets/140126906/4e92fa3a-f4de-485c-8e4e-65ecd3d5fd47)

The images are overlapping the above information above them.

**Comment by Amitanand0123** [comment]
@piug-07 Please assign me this issue. I will modify the styling of the section to give gap between them so that it looks clean.
Thank you:)

**Comment by dvnshi** [comment]
Please assign me this issue

**Comment by kashi-verma** [comment]
Please assign me this issue @piug-07 I will modify the styling of the section to give gap between them so that it looks clean make the UI more attractive.

Thank You

**Comment by mfatima05** [comment]
I have assigned this issue to both of you. The best solution will be merged.

**Comment by kashi-verma** [comment]
thanks for assigning this @mfatima05
