### ISSUE TITLE
Feature : Adding Login Signup pages 

### ISSUE THREAD

**Issue by HK853** [piyushg-07/blogzen-OpenSource#311]
![image](https://github.com/piug-07/blogzen-OpenSource/assets/113816862/838fa707-91a8-48f0-8185-90006478b1fa)

Like this. Can you assign me this feature under GSSoC with level

**Comment by mfatima05** [comment]
I have assigned you. Also don't remove the existing sign in with yahoo, google etc. options

**Comment by HK853** [comment]
ok on clicking the sign with goggle , yahoo and other options  i redirect to the login page.

**Comment by mfatima05** [comment]
no you can do it like this
![Screenshot 2024-06-01 121951](https://github.com/piug-07/blogzen-OpenSource/assets/112624853/571cddb0-bd8c-4e54-acd6-d4d4dfac4c42)

**Comment by HK853** [comment]
https://github.com/piug-07/blogzen-OpenSource/assets/113816862/a014f577-5102-4536-9f08-bc0d82860e6a

What is the Issue in my PR?

**Comment by DeepikaSidda** [comment]
### Feature

**Adding Login Signup pages**

_I would like to resolve this issue. Could you please assign this task to me under GSSOC'24._

### Record

- [ ] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue
