### ISSUE TITLE
Add a blog on "Introduction to DevOps" 

### ISSUE THREAD

**Issue by Devaki01** [piyushg-07/blogzen-OpenSource#314]
### Description of the issue 
I would like to add another blog to share my knowledge of DevOps by adding an "Introduction to DevOps " blog. The blog will be informative as well as beginner-friendly.

### About me 
Hello, my name is Devaki Joshi. I am a tech-enthusiast, specially passionate about front-end technologies and DevOps. As a GGSoC'24 contributor, I am really eager to make the proposed contributions and looking forward to learn more in the process.

Can you please assign me this issue under ggsoc'24

**Comment by mfatima05** [comment]
Assigned it. Now you can work on this issue.

**Comment by Devaki01** [comment]
Thank you.
