### ISSUE TITLE
BUG : Calendar and Log in button on the navbar do not have hover effect 

### ISSUE THREAD

**Issue by Devaki01** [piyushg-07/blogzen-OpenSource#317]
**Description**
In the navbar, the the calendar and log in button do not have hover effect even though sign up button has. 

![20240601_135145](https://github.com/piug-07/blogzen-OpenSource/assets/147143243/49efbfdc-c5a9-47cb-9664-a09e524cc715)
![20240601_135236](https://github.com/piug-07/blogzen-OpenSource/assets/147143243/32967d7c-b180-4b5d-a1fc-b93574fc0cfa)

Can you please assign me this issue under ggsoc'24 ?

**Comment by Ananya-Nair20** [comment]
Hello @piug-07

I am participating in GSSOC'24. I am interested in resolving this issue. Please assign this issue to me under GSSOC'24 with appropriate level labels.

Thank you
