### ISSUE TITLE
hover effect on different news boxes and in nav bar

### ISSUE THREAD

**Issue by Shreyaa173** [piyushg-07/blogzen-OpenSource#321]
![image](https://github.com/piug-07/blogzen-OpenSource/assets/144673309/b1ea5370-2901-45dc-9f17-330af77572a8)
![Screenshot 2024-06-01 160830](https://github.com/piug-07/blogzen-OpenSource/assets/144673309/30643c96-dcd9-4da1-9a6a-959dec51f2ce)
want to add hover effect in all these

**Comment by mfatima05** [comment]
Assigned

**Comment by jyotisoni24** [comment]
Please assign this issue to me

**Comment by Shreya173** [comment]
This is already assigned to me and I have submitted the PR also

**Comment by Shreyaa173** [comment]
Hey plz merge my PR #378

**Comment by jyotisoni24** [comment]
Ohh.. ok sorry.. actually I am doing open source for the first time, that's
why I didn't know it before.
