### ISSUE TITLE
Adding Hover Effect to Options and Identified a Unresponsive option

### ISSUE THREAD

**Issue by sailaja-adapa** [piyushg-07/blogzen-OpenSource#352]
Hello Mam, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i seen a issue about the buttons that are below the search box when i am first opened the project intially the the effect is on "All" but later when i switched to another option and again clicking on "All" it is not at all showing any effect and also i had a thought of changing that effect to hover  as it is not so attractive as you can see in this video. Due to the size of the option it is making the effect unattractive  

https://github.com/piug-07/blogzen-OpenSource/assets/161804629/ea9f71d6-ac2c-4ee6-85b5-6b4f5a6e03f0

Can you please assign me this issue under gssoc'24

**Comment by Pratiksha1661** [comment]
Please assign me this issue under GSSOC'24 .
