### ISSUE TITLE
Adding styles to navbar as it looks simple and styling buttons

### ISSUE THREAD

**Issue by SuhainaFathimaM** [piyushg-07/blogzen-OpenSource#358]
Adding styles to navbar as it looks simple and styling buttons

Adding styles and animations

![image](https://github.com/piug-07/blogzen-OpenSource/assets/153417476/e3d0693a-a5ee-4cec-bd22-f2d7c363bfdf)

**Comment by SuhainaFathimaM** [comment]
@piug-07 I am a GSSoC Contributor . I would like to work on this issue. Please assign me this issue.

**Comment by DrishtiRai777** [comment]
Hello,

My name is Drishti Rai. I am eager to apply my front-end development and design skills to make a meaningful contribution to this aspect of the project. Could you please assign this issue to me?

Thank you.
