### ISSUE TITLE
No Hover effect of this category

### ISSUE THREAD

**Issue by MuraliDharan7** [piyushg-07/blogzen-OpenSource#362]
I want to add hover effect for the below category in the image.

![image](https://github.com/piug-07/blogzen-OpenSource/assets/130668745/e2042671-570a-4231-8ba2-2d6e911658cc)

The category is not having hover effect. This would confuse where are we clicking. 

Please assign this issue to me under GSSoC'24. Add relevant labels into it.

**Comment by DrishtiRai777** [comment]
Hello,

My name is Drishti Rai. I am interested in enhancing the footer style of this project to improve its overall look and feel.

I am eager to apply my front-end development and design skills to make a meaningful contribution to this aspect of the project. Could you please assign this issue to me?

Thank you.
