### ISSUE TITLE
Copyright section is not there at the footer

### ISSUE THREAD

**Issue by MuraliDharan7** [piyushg-07/blogzen-OpenSource#363]
Copyrights section is missing at the footer. This should be available all of the websites.

![image](https://github.com/piug-07/blogzen-OpenSource/assets/130668745/0f0711e6-5428-4f7d-94e2-e1eb07f23005)

Please assign this issue to me under GSSoC'24.

**Comment by pragneshborad** [comment]
I would like to work on this issue @piug-07 , please assign me this issue.
