### ISSUE TITLE
Add a bookmark option

### ISSUE THREAD

**Issue by avanimathur** [piyushg-07/blogzen-OpenSource#374]
Each blog should have a bookmark button so that the user can save articles for reading later.

![4](https://github.com/piug-07/blogzen-OpenSource/assets/151984867/e6176bc8-fbd3-4432-b0f8-3ae4977ff3f0)

This is under GSSOC'24.

Please assign it to me. 
Thanks

**Comment by puneet426** [comment]
Bookmark is important to select please assign it to me
