### ISSUE TITLE
Add padding in the boxes of Technologies

### ISSUE THREAD

**Issue by swaraj-das** [piyushg-07/blogzen-OpenSource#376]
### Problem: 
There is no padding and margin outside of those boxes in which the technologies are written.

I am eager to take on this task and contribute to improving the responsiveness of the website. Please assign this issue to me under GSSOC"24
![1](https://github.com/piug-07/blogzen-OpenSource/assets/151845349/4647401a-72e6-48e1-bc14-2cccac6508cc)

**Comment by Pratiksha1661** [comment]
Please assign this issue to me under GSSOC"24

**Comment by student-singh** [comment]
I would like to work on this issue .Please assign it to me under GSSOC'24
