### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by Ishmeetkaur36** [piyushg-07/blogzen-OpenSource#387]
header buttons spell check needed

@piug-07 assign it to me

**Comment by Poonam-Kashyap12** [comment]
@Ishmeetkaur36  can u send the picture or tell in brief where is spell mistake ??

**Comment by Ishmeetkaur36** [comment]
well that has been corrected now but the hover and size of login sign up calendar buttons isn't uniform,

![Screenshot 2024-06-17 185759](https://github.com/piug-07/blogzen-OpenSource/assets/164319173/5095c9c7-edaf-4e19-834f-c2c8d7c0f6c2)
here in the mind reading technology blog don't seems more appropriate

**Comment by Poonam-Kashyap12** [comment]
@Ishmeetkaur36 thanku
