### ISSUE TITLE
FEATURE: add more social media 

### ISSUE THREAD

**Issue by jayanththalla** [piyushg-07/blogzen-OpenSource#393]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

I want to add more social media like LinkedIn, discord, and GitHub.
hover with different colors 
please assign me @pa

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by Shahbaz898414** [comment]
assign me plz

**Comment by Poonam-Kashyap12** [comment]
I want to work on this issue
