### ISSUE TITLE
BUG:DAYS ARE NOT VISSIBLE OF CALENDER ON DARK MODE

### ISSUE THREAD

**Issue by AbhinaySngh** [piyushg-07/blogzen-OpenSource#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-06 135131](https://github.com/piug-07/blogzen-OpenSource/assets/162811933/1736a2f3-44b8-49cd-b398-9a2b83a54d81)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AbhinaySngh** [comment]
@piug-07 please assign me this issue under GSSOC'24 label.

**Comment by Arifkhankhankhankhan** [comment]
I would like to work on this issue. Can you assign it to me and add the GSSOC'24 label?
