### ISSUE TITLE
THE TWITTER ICON SHOULD BE REPLACED WITH "X"

### ISSUE THREAD

**Issue by GAGGZ1** [piyushg-07/blogzen-OpenSource#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

THERE SHOULD BE "X" ICON
![image](https://github.com/piug-07/blogzen-OpenSource/assets/81284966/7dba6e7b-d2c8-4bc2-ad77-7fa3b17fc73b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by GAGGZ1** [comment]
@piug-07 please assign me this issue as i know FrontEnd Web Development

**Comment by gagan-bhullar-tech** [comment]
@piug-07 I am looking to contribute to open source. Request you to please assign this to me.

**Comment by GAGGZ1** [comment]
@piug-07  please assign me this issue as i know FrontEnd Web Development

**Comment by aditya1492025** [comment]
@piug-07 
I would like to work on this issue to replace the Twitter icon with "X" as mentioned in issue. I have experience with front-end development and design, and I can make sure the new icon aligns with the existing design aesthetics of the project.

Could you please assign this issue to me? I'll start working on the changes right away.

Thank you!

**Comment by GAGGZ1** [comment]
@piug-07  please assign me this issue as i know FrontEnd Web Development

**Comment by Poonam-Kashyap12** [comment]
I want to work on this issue

**Comment by AnshRehan04** [comment]
@piug-07  I would like to work on this issue.Please assign me with this issue.
Thank You.
