### ISSUE TITLE
FEATURE: adding social medial icon in follow us section

### ISSUE THREAD

**Issue by dnyandeepchute** [piyushg-07/blogzen-OpenSource#437]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

adding other social medial icon like linkedin in follow us section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by tanishirai** [comment]
I can work on this issue
