### ISSUE TITLE
BUG: chatbot color

### ISSUE THREAD

**Issue by taneeshaa15** [piyushg-07/blogzen-OpenSource#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@piug-07 Please address issue #289 and assign me under gssoc'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by pallabisneha** [comment]
I want to work on this issue under gssoc 2024, Please assign me this.....thank you 😊
