### ISSUE TITLE
FEATURE:Dockerize the app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [piyushg-07/blogzen-OpenSource#464]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

I want to tell you that we have to dockerize the app because when in future anyone want to clone our app and use our app in different operating system then our project dont run in their system so for removing this problem we have to dockerize the app so that everyone can easily use our app
You can also publish your app in docker hub from where user can run your project by simply one command

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by vedantterse** [comment]
@piug-07 can I work on this issue?
