### ISSUE TITLE
FEATURE: update the UI of Date

### ISSUE THREAD

**Issue by DevGajjar28** [piyushg-07/blogzen-OpenSource#481]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

Date UI is not good experience for users , 
![image](https://github.com/piug-07/blogzen-OpenSource/assets/145287513/2a8d5a36-4850-4cf7-a47a-4a7903c28cc9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by bheemajayashreee** [comment]
please assign this issue to me!!

**Comment by DevGajjar28** [comment]
submitted PR #483
