### ISSUE TITLE
Chat Interface Error Notification

### ISSUE THREAD

**Issue by narayani9120** [piyushg-07/blogzen-OpenSource#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The ChatBot is not working correctly.
![Screenshot 2024-06-09 184557](https://github.com/piug-07/blogzen-OpenSource/assets/125353066/2cd0110e-175d-49e1-9564-d287c322d0a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Erick-254** [comment]
Is the API key and endpoint URL correct?
