### ISSUE TITLE
Login, SignUp buttons

### ISSUE THREAD

**Issue by bheemajayashreee** [piyushg-07/blogzen-OpenSource#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Make sure both login and signUp buttons have same  styling.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by SeanAverS** [comment]
Hello, 

I am interested on working on this. Could I please be assigned? Thank you.
