### ISSUE TITLE
Footer Content Enhancement

### ISSUE THREAD

**Issue by Khushishah224** [piyushg-07/blogzen-OpenSource#535]
### What would you like to share?

-The Current Footer does not contain the Privacy & Terms section and copyright right up which can cause trouble in the future for 
 copyright. 
-It's good to add the Privacy & Terms section and copyright right up these sections in the Footer.

**Describe the solution you'd like**
-For the Footer section I would like to add the Privacy & Terms section and copyright right up.

## Please assign this issue to me, I want to work on this issue. 

***Are you contributing under any open-source program ?***
   -I'm a GSSOC'24 contributor
   -Please give it a gssoc'24 label and assign this work to me.

**Comment by neeleshkr22** [comment]
please assign me this work
