### ISSUE TITLE
BUG: Replace the icon of netlify in Footer Section

### ISSUE THREAD

**Issue by Deepanshi-05** [piyushg-07/blogzen-OpenSource#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Netlify icon in the footer section is like the Spotify icon. We can replace it with the original Netlify icon.

![i,mm](https://github.com/piug-07/blogzen-OpenSource/assets/158538244/9a7aea4a-7255-4e63-9a23-621e10cd83a9)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by guneetdewangan9** [comment]
I would like to solve this issue. Please assign me this issue under GSSoC'24 to make contribution to this project.
