### ISSUE TITLE
FEATURE: Add Sign Up page

### ISSUE THREAD

**Issue by HimangshuRanjan** [piyushg-07/blogzen-OpenSource#542]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

Adding a sign up page and improve log in page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by Nishantkumar012** [comment]
@HimangshuRanjan  is this issue still open
