### ISSUE TITLE
FEATURE:  Add github icon and linkedln icon on footer section

### ISSUE THREAD

**Issue by Deepanshi-05** [piyushg-07/blogzen-OpenSource#545]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

Most sites contain GitHub and LinkedIn icon in the footer section so that users can access their accounts easily.
Therefore, we should add those icons in footer section.

![Screenshot (19)](https://github.com/piug-07/blogzen-OpenSource/assets/158538244/e0608f7b-5f12-428d-a028-13f55815d144)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by guneetdewangan9** [comment]
I would like to solve this issue. Please assign me this issue under GSSoC'24 to make contribution to this project.
