### ISSUE TITLE
BUG:Replace the Twitter icon with X 

### ISSUE THREAD

**Issue by Braj-01** [piyushg-07/blogzen-OpenSource#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Twitter is now changed to X and icon also gets changed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Braj-01** [comment]
Please assign me this task so that I can start work on it under GSSOC'24.

**Comment by Subashree-selvaraj** [comment]
can i resolve this issue??
