### ISSUE TITLE
BUG: Missing of socials at the footer of Login Page

### ISSUE THREAD

**Issue by Chandana-756** [piyushg-07/blogzen-OpenSource#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In login page I have noticed that socials are missing under Follow us on our socials which is located at the footer of the login page.

![image](https://github.com/piug-07/blogzen-OpenSource/assets/94692989/76c128bf-232a-4ebf-a197-674be48e0884)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by claireoe** [comment]
@Chandana-756 I would like to work on this. Please assign me this task so that I can start work on it under GSSOC'24.

**Comment by Bliss011** [comment]
Please assign me this task
