### ISSUE TITLE
BUG: The LOGIN button is out of style 

### ISSUE THREAD

**Issue by jeevikasirwani** [piyushg-07/blogzen-OpenSource#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The style of all the buttons is not the same (Login button)
![Screenshot (301)](https://github.com/piug-07/blogzen-OpenSource/assets/83456541/59f01f34-765e-44d1-b932-bf2368311d41)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by Yugalgarg2002** [comment]
#581 I have covered this issue in my PR.
