### ISSUE TITLE
BUG: The theme logo turns extremely small 

### ISSUE THREAD

**Issue by jeevikasirwani** [piyushg-07/blogzen-OpenSource#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The theme logo turns extremely small  on the login page almost like its not visible 
![Screenshot (300)](https://github.com/piug-07/blogzen-OpenSource/assets/83456541/70710f1c-7e48-4cd8-abb5-439a4cb8d28a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by HoHoHoCCH** [comment]
The issue was the `box-sizing: border-box;` applied onto the body's decendants for the login page that caused the logo to be smaller. I made a pull request addressing this issue.
