### ISSUE TITLE
Adding sign up page 

### ISSUE THREAD

**Issue by Its-your-rj** [piyushg-07/blogzen-OpenSource#575]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

<img width="946" alt="Screenshot 2024-06-15 101908" src="https://github.com/piug-07/blogzen-OpenSource/assets/131703345/ee319255-fcc1-492b-8f19-c4d717c5f7b3">
There is no sign up page in this website please allow me to build up new sign up page along with proper styling and syntaxing.
please assign me this task under gssoc level3 it would be a great help to me .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by shivansh84ya** [comment]
Could you please assign this issue to me?
