### ISSUE TITLE
BUG: Social Media Links Redirect to Home Page Instead of Respective Profiles

### ISSUE THREAD

**Issue by Amishachoudhary22** [piyushg-07/blogzen-OpenSource#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The social media links on the page currently redirect to the home page instead of the respective social media profiles. This issue affects the user experience, as users are unable to visit the social media profiles  directly from the page.
Expected Behavior:
Each social media link should direct users to the correct social media profile.

Actual Behavior:
The social media links redirect users to the home page.

<img width="467" alt="Screenshot 2024-06-15 at 9 03 51 PM" src="https://github.com/piug-07/blogzen-OpenSource/assets/103454929/1134343a-ff19-4fd6-a07c-e1364c30bde4">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by khushig28** [comment]
I would to solve this issue. Please assign it to me
