### ISSUE TITLE
BUG:  Missing icons in the website from the figma file

### ISSUE THREAD

**Issue by MaruthiSingh** [piyushg-07/blogzen-OpenSource#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have made changes to the website according to the figma I want to push these changes to main branch.

Before:
![image](https://github.com/piug-07/blogzen-OpenSource/assets/103304179/12010a98-0aee-4176-8017-ccb85e920fe2)

After:
![image](https://github.com/piug-07/blogzen-OpenSource/assets/103304179/c52d37a3-1689-4322-9eab-ed89bbcbc43f)

Changes added background image to the search input and also icon in calendar and search  

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by claireoe** [comment]
@MaruthiSingh Please assign this issue to me ?
