### ISSUE TITLE
BUG:Bug in chatbot

### ISSUE THREAD

**Issue by Anjaliavv51** [piyushg-07/blogzen-OpenSource#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Chatbot is responding properly.

### Screenshot

![image](https://github.com/piug-07/blogzen-OpenSource/assets/154777864/5989f221-793c-47df-bf29-02f132e2aa7b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Bliss011** [comment]
Can you please assign me this task
