### ISSUE TITLE
FEATURE: Improving Color code for login

### ISSUE THREAD

**Issue by kashisharora9462** [piyushg-07/blogzen-OpenSource#613]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

While the website looks great in light mode, I noticed the login option vanishes in dark mode. This can be frustrating for users.  I can fix this by making the login option text white, so it shows up clearly on the dark background. On top of that, I can also update the font style to give it a more modern feel. This small change will make the login process smoother and more visually appealing in dark mode.

![image](https://github.com/piug-07/blogzen-OpenSource/assets/153215875/0f32f2c6-f48a-4d97-803b-d74863494c14)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by kashisharora9462** [comment]
I have improved the design by changing the login button color to white. This makes it more visually appealing and easier for users to see.
![image](https://github.com/piug-07/blogzen-OpenSource/assets/153215875/93f03dd7-65c4-48f0-a7eb-8ad3b3e331c1)

**Comment by Babuprasanth27** [comment]
@kashisharora9462 Greetings, I am interested in fixing this issue. Could you assign it to me?
