### ISSUE TITLE
FEATURE: Add social media accounts links in login page footer

### ISSUE THREAD

**Issue by Gultreen** [piyushg-07/blogzen-OpenSource#615]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

In this feature, I am adding the social media accounts in the Follow Us section of the login page footer.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by Babuprasanth27** [comment]
Hey, I am interested in fixing this issue.
