### ISSUE TITLE
FEATURE: 'search' text in search placeholder.

### ISSUE THREAD

**Issue by code-sans** [piyushg-07/blogzen-OpenSource#620]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

I want that text "search" in search placeholder should be in the middle and I can do that by adding some CSS in it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by Babuprasanth27** [comment]
@code-sans  Greetings, I am interested in fixing this issue. Could you assign it to me?

**Comment by shivansh84ya** [comment]
Could you please assign this issue to me?
