### ISSUE TITLE
The rise of AI image is not visible

### ISSUE THREAD

**Issue by shivathmikavemula** [piyushg-07/blogzen-OpenSource#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The rise of AI image is not visible
### Screenshot -
![Screenshot (32)](https://github.com/piug-07/blogzen-OpenSource/assets/133566953/322e2189-3b63-4118-8373-6ab37177d9fe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by shivathmikavemula** [comment]
Please assign me this issue @piug-07

**Comment by Karthikkariappa08** [comment]
plz assign this task to me

**Comment by Karthikkariappa08** [comment]
plz asign this task to me

**Comment by shivathmikavemula** [comment]
completed the task 
PR no: 622
@piug-07 
please assign the gssoc levels to it.

**Comment by GOURAV-VERMAA** [comment]
Hi,

I noticed that the image related to "The rise of AI " #621 is not visible. Could you please assign this issue to me? I would like to investigate and resolve it.
