### ISSUE TITLE
FEATURE: Adding Cursor Animation

### ISSUE THREAD

**Issue by SagarRathore1** [piyushg-07/blogzen-OpenSource#628]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

I would like to add cursor animation to the website which makes website look more attractive and professional.It will enhance user experience .

![Screenshot 2024-06-17 121136](https://github.com/piug-07/blogzen-OpenSource/assets/169483518/255de19a-ed32-4123-b695-64a19de5bf50)

https://github.com/piug-07/blogzen-OpenSource/assets/169483518/f8c97dc1-679a-49f9-ae14-4064083b2d91

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by nafreenanjum** [comment]
please assign me this work
