### ISSUE TITLE
DOCS:social media link is not present in 

### ISSUE THREAD

**Issue by kavyachandarkar** [piyushg-07/blogzen-OpenSource#632]
### What documentation needs updating?

<img width="951" alt="image" src="https://github.com/piug-07/blogzen-OpenSource/assets/156076079/810bb5b8-8090-4f5a-968e-417e7516609e">
here as you can see your social media links are not declared 
i want to add them along with logo 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on updating the documentation

**Comment by Babuprasanth27** [comment]
Hey, I am interested in fixing this issue.

**Comment by Babuprasanth27** [comment]
@kavyachandarkar Hello could you please assign it to me

**Comment by Massa-Albani4** [comment]
im interested can i work on this?

**Comment by Babuprasanth27** [comment]
@Massa-Albani4 I too interested in fixing this issue.

**Comment by Bliss011** [comment]
Can i work on this issue
