### ISSUE TITLE
DOCS:want to add a better logo

### ISSUE THREAD

**Issue by kavyachandarkar** [piyushg-07/blogzen-OpenSource#633]
### What documentation needs updating?

want to change logo and want to make it more authentic

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on updating the documentation

**Comment by Babuprasanth27** [comment]
Hey, I am interested in fixing this issue.

**Comment by Babuprasanth27** [comment]
@kavyachandarkar Hello? Could you assign it to me?

**Comment by nafreenanjum** [comment]
please assign me this work

**Comment by neeleshkr22** [comment]
please assign me this work
