### ISSUE TITLE
Need Navbar for Mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [piyushg-07/blogzen-OpenSource#640]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

The website needs Navbar for Mobile screen

![image](https://github.com/piug-07/blogzen-OpenSource/assets/124615886/1e1e4be3-3f09-4c27-800a-c6a086d1c826)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by Babuprasanth27** [comment]
@Utsavladia Greetings, I am interested in fixing this issue.Could you assign it to me?

**Comment by Utsavladia** [comment]
@Babuprasanth27  
I am already working on it under GSSoC 
you can explore other issues or create your own if there is any issue 😊

**Comment by Babuprasanth27** [comment]
@Utsavladia OK No worries Go ahead.
