### ISSUE TITLE
FEATURE: Make website responsive

### ISSUE THREAD

**Issue by RahulK4102** [piyushg-07/blogzen-OpenSource#641]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

make the website responsive
![image](https://github.com/piug-07/blogzen-OpenSource/assets/119075798/703488fd-e72e-4bbf-8741-3b56061f0cef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by Babuprasanth27** [comment]
@RahulK4102 Greetings, I am interested in fixing this issue. Could you assign it to me?

**Comment by RahulNaha** [comment]
Willing to fix this issue. Could you assign it to me? @RahulK4102

**Comment by shivansh84ya** [comment]
Could you please assign this issue to me?

**Comment by shresh15** [comment]
I want to fix this issue..could you assign it to me

**Comment by Nihalsingh19** [comment]
@RahulK4102 , I am interested in fixing this issue. Could you assign it to me?

**Comment by Priyasharma02821** [comment]
Hello, I'm interested in fixing this issue. Can you please assign this to me?
