### ISSUE TITLE
FEATURE: LOGIN PAGE UPGRADE

### ISSUE THREAD

**Issue by AbheetHacker4278** [piyushg-07/blogzen-OpenSource#645]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

![image](https://github.com/piug-07/blogzen-OpenSource/assets/114290748/1d53d32e-9b2a-4a30-a157-592740f58f5b)

Login page look very basic  , i want to improve the login and signup page with good UI-UX.

@piug-07  please assign this PR to me under GSSOC24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by AbheetHacker4278** [comment]
@piug-07 please assign this under GSSOC24

**Comment by nafreenanjum** [comment]
assign me this work.

**Comment by AbheetHacker4278** [comment]
@nafreenanjum i want to work on this issue
