### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by TheNikhilRaj** [piyushg-07/blogzen-OpenSource#651]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

Hey @piug-07  ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

Screenshot(Mandatory):

![Capture](https://github.com/piug-07/blogzen-OpenSource/assets/129590267/131ea915-bfae-4373-899a-5813ebf0b0fa)

@piug-07  ,Could you please assign me this issue under gssoc'24 ?

Are you contributing under any open-source program ?
GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by Bliss011** [comment]
Can you please assign me this task.
