### ISSUE TITLE
BUG: Navigation light dark mode and calendar button not working

### ISSUE THREAD

**Issue by himanshik21** [piyushg-07/blogzen-OpenSource#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I go to login page the light dark mode button goes very tiny and not able to work when i click on it , also the calendar is not showing when i click on calendar, so this is a one of the not major bug, but must be consider as a bug.
And I want resolve this bug with optimized functionalities.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by himanshik21** [comment]
thank you for giving me this opportunity, can you assign me again this issue to resolve , as i accidentally remove the assignment.
In future, there is thing like will not happen

**Comment by Bliss011** [comment]
Can you please assign me this issue
