### ISSUE TITLE
FEATURE: Hover effect 

### ISSUE THREAD

**Issue by ANIRUDH130903** [piyushg-07/blogzen-OpenSource#657]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

AS, WE HOVER THE SECTION WE CAN MAKE THAT SECTION ENLARGE. WHICH MAKE THAT MORE ATTRACTIVE AND CATCHIER
![Screenshot 2024-07-01 140457](https://github.com/piug-07/blogzen-OpenSource/assets/129547564/71c3e703-05e4-4b42-959e-991d5be8849e)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by ANIRUDH130903** [comment]
@piug-07 can please assign me this task.

**Comment by ANIRUDH130903** [comment]
@piug-07 can I please work on this issue

**Comment by Soujanya2004** [comment]
hi, I have been following your project and would love to contribute, please assign me the issue.
