### ISSUE TITLE
FEATURE: Improvising the UI styling of the website

### ISSUE THREAD

**Issue by SiddhiT28** [piyushg-07/blogzen-OpenSource#662]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

Improvise the UI to match the design in the Figma file.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by adinathraut** [comment]
hey @piug-07 I have worked on it kindly assign it to me

**Comment by SiddhiT28** [comment]
I have been working on the change and am about to raise a PR. As it was already assigned to me
