### ISSUE TITLE
FEATURE:  Adding a scroll to the top button

### ISSUE THREAD

**Issue by Rajul-29** [piyushg-07/blogzen-OpenSource#676]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

Clicking the button smoothly scrolls the user back to the top of the page
Provides a smooth scroll animation to the top
Button is fixed at the bottom right corner of the viewport

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by kashi-verma** [comment]
pls assign me this issue @piug-07
