### ISSUE TITLE
BUG:Change the twitter icon at Footer

### ISSUE THREAD

**Issue by jennifereunice** [piyushg-07/blogzen-OpenSource#689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/522dfe5a-24be-449f-a184-618e66b86c8f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by ananyabansal16** [comment]
Hey, if this issue is still pending, I can work on this.
