### ISSUE TITLE
BUG:Signup button is not working

### ISSUE THREAD

**Issue by jennifereunice** [piyushg-07/blogzen-OpenSource#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/7c060193-a4ce-4a99-9aae-9184b5365b49)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by anshulagr5** [comment]
I would like to work on this issue. Kindly assign it to me.
